import rose from "./images/roses.jpeg"

export const flowers = [
  {
    id: 1,
    name: "Red Roses Bouquet",
    price: 45.99,
    image: rose,
    category: "Roses",
    rating: 4.8,
    description: "Beautiful red roses perfect for romantic occasions",
    inStock: true,
  },
  {
    id: 2,
    name: "Sunflower Arrangement",
    price: 32.99,
    image: rose,
    category: "Sunflowers",
    rating: 4.6,
    description: "Bright and cheerful sunflowers to brighten any day",
    inStock: true,
  },
  {
    id: 3,
    name: "White Lilies",
    price: 38.99,
    image: rose,
    category: "Lilies",
    rating: 4.7,
    description: "Elegant white lilies for special moments",
    inStock: true,
  },
  {
    id: 4,
    name: "Mixed Tulips",
    price: 29.99,
    image: rose,
    category: "Tulips",
    rating: 4.5,
    description: "Colorful tulips bringing spring vibes",
    inStock: false,
  },
  {
    id: 5,
    name: "Pink Peonies",
    price: 52.99,
    image: rose,
    category: "Peonies",
    rating: 4.9,
    description: "Luxurious pink peonies for elegant occasions",
    inStock: true,
  },
  {
    id: 6,
    name: "Lavender Bundle",
    price: 24.99,
    image: rose,
    category: "Herbs",
    rating: 4.4,
    description: "Fragrant lavender bundle for relaxation",
    inStock: true,
  },
  {
    id: 7,
    name: "Orchid Plant",
    price: 65.99,
    image: rose,
    category: "Orchids",
    rating: 4.8,
    description: "Exotic orchid plant for long-lasting beauty",
    inStock: true,
  },
  {
    id: 8,
    name: "Daisy Bouquet",
    price: 26.99,
    image: rose,
    category: "Daisies",
    rating: 4.3,
    description: "Fresh white daisies for simple elegance",
    isLiked: false,
    inStock: true,
  },
]
